# Site settings
title: Clarissa Fonseca
email: your-email@domain.com
url: https://cpsf1313.github.io
description: "This is my space, where I post my work and thoughts. I am glad you have stopped by :)."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Clarissa Fonseca
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ClarisFonseca
  - title: facebook
    url: https://www.facebook.com/groups/729580157120904/
  - title: instagram
    url: http://instagram.com/boomshaka_clari/
  - title: linkedin
    url: https://www.linkedin.com/pub/clarissa-fonseca/97/7a7/ab5/en
  - title: github
    url: https://github.com/cpsf1313

# Postal address (add as many lines as necessary)
address:
  - line: Everywhere and nowhere ;)


# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
